
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.time.LocalDate;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author SD10058954
 */
public class AddApplicant extends javax.swing.JFrame {

    /**
     * Creates new form AddMemb
     */
    public AddApplicant() {
        initComponents();
        Color b = new Color(180, 200, 170);
        getContentPane().setBackground(b);
        BackgroundMusic.play("src/bgmusic.wav");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblFn = new javax.swing.JLabel();
        lblSn = new javax.swing.JLabel();
        lblPn = new javax.swing.JLabel();
        lblIn = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txfFn = new javax.swing.JTextField();
        txfSn = new javax.swing.JTextField();
        spnAge = new javax.swing.JSpinner();
        txfPn = new javax.swing.JTextField();
        btnAddApplicant = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        lblYoE = new javax.swing.JLabel();
        spnYe = new javax.swing.JSpinner();
        dpAppDate = new com.github.lgooddatepicker.components.DatePicker();
        lblFirstNameErr = new javax.swing.JLabel();
        lblSurnameErr = new javax.swing.JLabel();
        lblPnERrr = new javax.swing.JLabel();
        lblyEerr = new javax.swing.JLabel();
        cBStatus = new javax.swing.JComboBox<>();
        lblDateErr = new javax.swing.JLabel();
        cBInstrument = new javax.swing.JComboBox<>();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitle.setText("Add Applicant");
        lblTitle.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N

        lblFn.setText("First Name:");
        lblFn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        lblSn.setText("Surname:");
        lblSn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        lblPn.setText("Phone Number:");
        lblPn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        lblIn.setText("Instruntment:");
        lblIn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        lblAge.setText("Age:");
        lblAge.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        lblDate.setText("Application Date:");
        lblDate.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        txfFn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfFnActionPerformed(evt);
            }
        });

        spnAge.setModel(new javax.swing.SpinnerNumberModel(18, 18, 40, 1));

        btnAddApplicant.setText("Add Applicant");
        btnAddApplicant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddApplicantActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        lblStatus.setText("Status:");
        lblStatus.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        lblYoE.setText("Years of Experience:");
        lblYoE.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        lblFirstNameErr.setText(" ");

        lblSurnameErr.setText(" ");

        lblPnERrr.setText("               ");

        lblyEerr.setText(" ");

        cBStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Accepted", "Rejected" }));
        cBStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBStatusActionPerformed(evt);
            }
        });

        lblDateErr.setText(" ");

        cBInstrument.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vocals", "Drums", "Electric Guitar", "Bass", "Keyboard", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblYoE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddApplicant, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addComponent(lblSn)
                            .addComponent(lblFn)
                            .addComponent(lblPn)
                            .addComponent(lblIn)
                            .addComponent(lblDate)
                            .addComponent(lblStatus)
                            .addComponent(lblAge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfSn, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(txfFn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFirstNameErr, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cBInstrument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(spnYe, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblyEerr, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(spnAge, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txfPn, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                    .addComponent(lblPnERrr, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(165, 165, 165)
                                    .addComponent(lblSurnameErr, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dpAppDate, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblDateErr, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitle)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblFirstNameErr))
                    .addComponent(txfFn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSn)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfSn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSurnameErr))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPn)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblPnERrr))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txfPn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnAge, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnYe, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYoE)
                    .addComponent(lblyEerr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIn)
                    .addComponent(cBInstrument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(cBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDate)
                        .addComponent(lblDateErr))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(dpAppDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAddApplicant, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        this.dispose();
        new ApplAdmin().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddApplicantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddApplicantActionPerformed

        int error = 0;
        //Checks on firstName:
        //Presence Check
        if (txfFn.getText().isBlank()) {
            error++;
            lblFirstNameErr.setText("Field cannot be empty");
        }
        //String Check
        if (!txfFn.getText().matches("[a-zA-Z]+")) {
            error++;
            lblFirstNameErr.setText("Field must contain only letters");
        }
        //Length check
        if (txfFn.getText().length() < 3 || txfFn.getText().length() > 20) {
            error++;
            lblFirstNameErr.setText("Field length not valid");
        }

        //Surname Checks:
        //Presence Check
        if (txfSn.getText().isBlank()) {
            error++;
            lblSurnameErr.setText("Field cannot be empty");
        }
        //String Check
        if (!txfSn.getText().matches("[a-zA-Z]+")) {
            error++;
            lblSurnameErr.setText("Field must contain only letters");
        }
        //Length check
        if (txfSn.getText().length() < 3 || txfSn.getText().length() > 20) {
            error++;
            lblSurnameErr.setText("Field length not valid");
        }

        //PhoneNumber Checks:
        //Length Check:
        if (!(txfPn.getText().length() == 10)) {
            error++;
            lblPnERrr.setText("Field Length not valid");
        }
        //Digit Check:
        if (!txfPn.getText().matches("\\d+")) {
            error++;
            lblPnERrr.setText("Field must only contain digits");
        }
        //Presence check
        if (txfPn.getText().isBlank()) {
            error++;
            lblPnERrr.setText("Field cannot be empty");

        }

        //Logic check for experience
        int age = (int) spnAge.getValue();
        int yearsExp = (int) spnYe.getValue();

        if (yearsExp > age - 18) {
            error++;
            lblyEerr.setText("Experience does not match age");
        }

        //Date check:
        LocalDate date = dpAppDate.getDate();
        if (date == null) {
            error++;
            lblDateErr.setText("Select a date!");
        } else if (date.isAfter(LocalDate.now())) {
            error++;
            lblDateErr.setText("Date cannot be in the future");
        }

        if (error == 0) {
            lblFirstNameErr.setText("");
            lblPnERrr.setText("");
            lblyEerr.setText("");
            lblSurnameErr.setText("");
            ApplicantManager am = new ApplicantManager();
            ApplicantObj ao;
            ao = new ApplicantObj(txfFn.getText(), txfSn.getText(),
                    txfPn.getText(), Integer.parseInt(spnAge.getValue().toString()), (String) cBInstrument.getSelectedItem(),
                    dpAppDate.toString(), cBStatus.getSelectedItem().toString(), Integer.parseInt(spnYe.getValue().toString()));
            am.addApplicant(ao);
            JOptionPane.showMessageDialog(this, "Added!");
        } else {
            JOptionPane.showMessageDialog(this, "Errors present");
        }

    }//GEN-LAST:event_btnAddApplicantActionPerformed

    private void txfFnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfFnActionPerformed

    }//GEN-LAST:event_txfFnActionPerformed

    private void cBStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBStatusActionPerformed

    }//GEN-LAST:event_cBStatusActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed

        SimpleHelp.show();
    }//GEN-LAST:event_btnHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMemb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMemb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMemb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMemb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddApplicant().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddApplicant;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHelp;
    private javax.swing.JComboBox<String> cBInstrument;
    private javax.swing.JComboBox<String> cBStatus;
    private com.github.lgooddatepicker.components.DatePicker dpAppDate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateErr;
    private javax.swing.JLabel lblFirstNameErr;
    private javax.swing.JLabel lblFn;
    private javax.swing.JLabel lblIn;
    private javax.swing.JLabel lblPn;
    private javax.swing.JLabel lblPnERrr;
    private javax.swing.JLabel lblSn;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSurnameErr;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblYoE;
    private javax.swing.JLabel lblyEerr;
    private javax.swing.JSpinner spnAge;
    private javax.swing.JSpinner spnYe;
    private javax.swing.JTextField txfFn;
    private javax.swing.JTextField txfPn;
    private javax.swing.JTextField txfSn;
    // End of variables declaration//GEN-END:variables
}
