
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DELL
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */
    public Help() {
        initComponents();
        Color b = new Color(180, 200, 170);
        getContentPane().setBackground(b);
        BackgroundMusic.play("src/bgmusic.wav");
        txfQuestion.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnAsk.doClick();
            }
        });
    }

    private boolean contains(String[] tokens, String word) {
        for (String token : tokens) {
            if (token.equalsIgnoreCase(word)) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        scpDisplay = new javax.swing.JScrollPane();
        txaDisplay = new javax.swing.JTextArea();
        btnAsk = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txfQuestion = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txaDisplay.setEditable(false);
        txaDisplay.setColumns(20);
        txaDisplay.setRows(5);
        scpDisplay.setViewportView(txaDisplay);

        btnAsk.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnAsk.setText("Ask");
        btnAsk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAskActionPerformed(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblHeading.setText("Help ChatBot");

        btnHelp.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txfQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfQuestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btnAsk)
                .addGap(79, 79, 79)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(btnHelp)
                .addGap(157, 157, 157))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(scpDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(txfQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(lblHeading)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(lblHeading)
                .addGap(60, 60, 60)
                .addComponent(txfQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scpDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHelp)
                    .addComponent(btnAsk)
                    .addComponent(btnBack))
                .addGap(98, 98, 98))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAskActionPerformed
        // Grab user’s question from combo box
        String userInput = (String) txfQuestion.getText();
        txfQuestion.setText("");
        txaDisplay.append("User: " + userInput + "\n");
        // Use NLP to break into tokens
        NLPProcessor nlp = new NLPProcessor();
        String[] tokens = nlp.tokenize(userInput);
        // Simple keyword-based logic with NLP
        if (contains(tokens, "add") && contains(tokens, "applicant")) {
            txaDisplay.append("ChatBot: To add an applicant, fill in all the required fields correctly. Ensure phone numbers are numeric and mandatory fields are not empty.\n");
        } else if (contains(tokens, "delete") && (contains(tokens, "applicant") || contains(tokens, "applicants"))) {
            txaDisplay.append("ChatBot: To delete an applicant, enter the applicant's ID and confirm deletion.\n");
        } else if (contains(tokens, "update") && contains(tokens, "applicant")) {
            txaDisplay.append("ChatBot: To update an applicant, input the applicant's ID and input correct values into all text fields\n");
        } else if (contains(tokens, "view") && contains(tokens, "applicants")) {
            txaDisplay.append("ChatBot: To view applicants, use the 'View' button in applicant admin\n");
        } else if ((contains(tokens, "add") || contains(tokens, "update") || contains(tokens, "delete")) && (contains(tokens, "error") || contains(tokens, "errors"))) {
            txaDisplay.append("ChatBot: Errors during add, update, or delete actions usually occur due to missing fields or invalid data types\n");
        } else if (contains(tokens, "add") && contains(tokens, "member")) {
            txaDisplay.append("ChatBot: To add a member, provide all required details such as name, instrument, and contact info. All entries must be the right type.\n");
        } else if (contains(tokens, "delete") && (contains(tokens, "members") || contains(tokens, "member"))) {
            txaDisplay.append("ChatBot: To delete a member, you must first enter their ID.\n");
        } else if (contains(tokens, "update") && (contains(tokens, "member") || contains(tokens, "members"))) {
            txaDisplay.append("ChatBot: To update a member, input their ID, then make changes to the fields shown.\n");
        } else if (contains(tokens, "view") && contains(tokens, "members")) {
            txaDisplay.append("ChatBot: To view members, use the 'View' function or search by name/ID to display relevant results.\n");
        } else if (contains(tokens, "add") && (contains(tokens, "event") || contains(tokens, "events"))) {
            txaDisplay.append("ChatBot: To add an event, provide event name, date, time, and location.etc. All fields must be valid.\n");
        } else if (contains(tokens, "delete") && (contains(tokens, "event") || contains(tokens, "events"))) {
            txaDisplay.append("ChatBot: To delete an event, enter its ID, then confirm.\n");
        } else if (contains(tokens, "update") && (contains(tokens, "event") || contains(tokens, "events"))) {
            txaDisplay.append("ChatBot: To update an event, input ID and modify all details.\n");
        } else if (contains(tokens, "view") && (contains(tokens, "event") || contains(tokens, "events"))) {
            txaDisplay.append("ChatBot: To view events, use the 'View Events' feature to see all upcoming or past events.\n");
        } else if (contains(tokens, "error") || contains(tokens, "errors")) {
            txaDisplay.append("ChatBot: All fields must be filled or have the right type of data.\n");
        } else if (contains(tokens, "search") && (contains(tokens, "applicant") || contains(tokens, "member") || contains(tokens, "event"))) {
            txaDisplay.append("ChatBot: In update or delete you can view the record with the matching ID before deleting or updating.\n");
        } else {
            txaDisplay.append("ChatBot: Sorry, I don’t understand that yet.\n");
        }

    }//GEN-LAST:event_btnAskActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed

        this.dispose();
        new MainScreen().setVisible(true);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        this.dispose();
        new MainScreen().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txfQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfQuestionActionPerformed

    }//GEN-LAST:event_txfQuestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsk;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHelp;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JScrollPane scpDisplay;
    private javax.swing.JTextArea txaDisplay;
    private javax.swing.JTextField txfQuestion;
    // End of variables declaration//GEN-END:variables
}
