
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author SD10058954
 */
public class UpdAppl extends javax.swing.JFrame {

    /**
     * Creates new form AddMemb
     */
    public UpdAppl() {
        initComponents();
        Color b = new Color(180, 200, 170);
        getContentPane().setBackground(b);
        BackgroundMusic.play("src/bgmusic.wav");
    }

    public void help() {
        try {

            Scanner scFile = new Scanner(new File("Help.txt"));
            String output = "";
            while (scFile.hasNext()) {
                String data = scFile.nextLine();
                output = output + data + "\n";
            }
            JOptionPane.showMessageDialog(null, output);
        } catch (FileNotFoundException ex) {
            System.out.println("File not found");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        lblApplicantID = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblPhoneNum = new javax.swing.JLabel();
        lblInstrument = new javax.swing.JLabel();
        lblApplDate = new javax.swing.JLabel();
        txfFn = new javax.swing.JTextField();
        txfPn = new javax.swing.JTextField();
        txfAppID = new javax.swing.JTextField();
        btnUpd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        txfSn = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblApplicantDetails = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        spnAge = new javax.swing.JSpinner();
        lblYearsExp = new javax.swing.JLabel();
        spnYe = new javax.swing.JSpinner();
        dpAppDate = new com.github.lgooddatepicker.components.DatePicker();
        lblFirstNameErr = new javax.swing.JLabel();
        lblSurnameErr = new javax.swing.JLabel();
        lblPnERrr = new javax.swing.JLabel();
        lblyEerr = new javax.swing.JLabel();
        lblMembIDerr = new javax.swing.JLabel();
        lblDateErr = new javax.swing.JLabel();
        scpDisplay = new javax.swing.JScrollPane();
        txaDisplay = new javax.swing.JTextArea();
        cBStatus = new javax.swing.JComboBox<>();
        cBInstrument = new javax.swing.JComboBox<>();
        lblApplErr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblHeading.setText("Update Applicant");
        lblHeading.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N

        lblApplicantID.setText("Applicant ID:");
        lblApplicantID.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        lblSurname.setText("Surname:");
        lblSurname.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        lblPhoneNum.setText("Phone Number:");
        lblPhoneNum.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        lblInstrument.setText("Instrument:");
        lblInstrument.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        lblApplDate.setText("Application Date:");
        lblApplDate.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        btnUpd.setText("Update Event");
        btnUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        lblFirstName.setText("First Name:");
        lblFirstName.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        lblApplicantDetails.setText("Applicant Details");
        lblApplicantDetails.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        lblStatus.setText("Status:");
        lblStatus.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        lblAge.setText("Age:");
        lblAge.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        spnAge.setModel(new javax.swing.SpinnerNumberModel(18, 18, 50, 1));

        lblYearsExp.setText("Years of Experience");
        lblYearsExp.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N

        lblFirstNameErr.setText(" ");

        lblSurnameErr.setText(" ");

        lblPnERrr.setText(" ");

        lblyEerr.setText(" ");

        lblMembIDerr.setText(" ");

        lblDateErr.setText(" ");

        txaDisplay.setColumns(20);
        txaDisplay.setEditable(false);
        txaDisplay.setRows(5);
        scpDisplay.setViewportView(txaDisplay);

        cBStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Accepted", "Rejected", " " }));

        cBInstrument.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vocals", "Drums", "Electric Guitar", "Bass", "Keyboard", " " }));

        lblApplErr.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPnERrr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPhoneNum))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSurnameErr, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSurname))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblyEerr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMembIDerr, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDateErr, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYearsExp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblInstrument, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblApplDate, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblApplErr, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblApplicantID)
                            .addComponent(lblStatus)
                            .addComponent(lblAge)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFirstNameErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFirstName)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfAppID, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txfPn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txfFn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txfSn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(2, 2, 2)))
                            .addComponent(dpAppDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(spnYe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addComponent(spnAge, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(cBInstrument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(cBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(lblApplicantDetails)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scpDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(296, 296, 296))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblHeading)
                        .addGap(437, 437, 437))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblHeading)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApplicantID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfAppID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApplErr))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfFn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFirstNameErr))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblApplicantDetails)
                                .addGap(5, 5, 5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSurname)
                            .addComponent(txfSn)
                            .addComponent(lblSurnameErr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhoneNum)
                            .addComponent(txfPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPnERrr))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus)
                            .addComponent(cBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(spnAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnYe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYearsExp)
                            .addComponent(lblyEerr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInstrument, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(lblMembIDerr)
                            .addComponent(cBInstrument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApplDate)
                            .addComponent(dpAppDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDateErr))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scpDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdActionPerformed
        int error = 0;
        if (!txfAppID.getText().matches("\\d+")) {
            error++;
            lblApplErr.setText("Field must consist only of digits");
        }

        if (txfAppID.getText().isBlank()) {
            error++;
            lblApplErr.setText("Field cannot be empty");
        }
        //Checks on firstName:
        //Presence Check
        if (txfFn.getText().isBlank()) {
            error++;
            lblFirstNameErr.setText("Field cannot be empty");
        }
        //String Check
        if (!txfFn.getText().matches("[a-zA-Z]+")) {
            error++;
            lblFirstNameErr.setText("Field must contain only letters");
        }
        //Length check
        if (txfFn.getText().length() < 3 || txfFn.getText().length() > 20) {
            error++;
            lblFirstNameErr.setText("Field length not valid");
        }

        //Surname Checks:
        //Presence Check
        if (txfSn.getText().isBlank()) {
            error++;
            lblSurnameErr.setText("Field cannot be empty");
        }
        //String Check
        if (!txfSn.getText().matches("[a-zA-Z]+")) {
            error++;
            lblSurnameErr.setText("Field must contain only letters");
        }
        //Length check
        if (txfSn.getText().length() < 3 || txfSn.getText().length() > 20) {
            error++;
            lblSurnameErr.setText("Field length not valid");
        }

        //PhoneNumber Checks:
        //Length Check:
        if (!(txfPn.getText().length() == 10)) {
            error++;
            lblPnERrr.setText("Field Length not valid");
        }
        //Digit Check:
        if (!txfPn.getText().matches("\\d+")) {
            error++;
            lblPnERrr.setText("Field must only contain digits");
        }
        //Presence check
        if (txfPn.getText().isBlank()) {
            error++;
            lblPnERrr.setText("Field cannot be empty");

        }

        //Logic check for experience
        int age = (int) spnAge.getValue();
        int yearsExp = (int) spnYe.getValue();

        if (yearsExp > age - 18) {
            error++;
            lblyEerr.setText("Experience does not match age");
        }

        //MemberID checks:
        //Presence
        //Date check:
        LocalDate date = dpAppDate.getDate();
        if (date == null) {

            error++;
            lblDateErr.setText("Select a date!");
        } else if (date.isAfter(LocalDate.now())) {
            error++;
            lblDateErr.setText("Date cannot be in the future");
        }

        if (error == 0) {
            lblApplErr.setText("");
            lblFirstNameErr.setText("");
            lblPnERrr.setText("");
            lblyEerr.setText("");
            lblSurnameErr.setText("");
            ApplicantManager am = new ApplicantManager();
            ApplicantObj ar = new ApplicantObj(Integer.parseInt(txfAppID.getText()), txfFn.getText(), txfSn.getText(),
                    txfPn.getText(), Integer.parseInt(spnAge.getValue().toString()), (String) cBInstrument.getSelectedItem(),
                    dpAppDate.toString().replace('T', ' '), cBStatus.getSelectedItem().toString(), Integer.parseInt(spnYe.getValue().toString()));
            am.updateApplicant(ar);

            JOptionPane.showMessageDialog(this, "Updated!");
        } else {
            JOptionPane.showMessageDialog(this, "Errors present");
        }


    }//GEN-LAST:event_btnUpdActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed

        ApplicantManager am = new ApplicantManager();
        txaDisplay.setText(am.findAppl(Integer.parseInt(txfAppID.getText())));
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        this.dispose();
        new ApplAdmin().setVisible(true);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed

        help();
    }//GEN-LAST:event_btnHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMemb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMemb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMemb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMemb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdAppl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnUpd;
    private javax.swing.JComboBox<String> cBInstrument;
    private javax.swing.JComboBox<String> cBStatus;
    private com.github.lgooddatepicker.components.DatePicker dpAppDate;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblApplDate;
    private javax.swing.JLabel lblApplErr;
    private javax.swing.JLabel lblApplicantDetails;
    private javax.swing.JLabel lblApplicantID;
    private javax.swing.JLabel lblDateErr;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFirstNameErr;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblInstrument;
    private javax.swing.JLabel lblMembIDerr;
    private javax.swing.JLabel lblPhoneNum;
    private javax.swing.JLabel lblPnERrr;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblSurnameErr;
    private javax.swing.JLabel lblYearsExp;
    private javax.swing.JLabel lblyEerr;
    private javax.swing.JScrollPane scpDisplay;
    private javax.swing.JSpinner spnAge;
    private javax.swing.JSpinner spnYe;
    private javax.swing.JTextArea txaDisplay;
    private javax.swing.JTextField txfAppID;
    private javax.swing.JTextField txfFn;
    private javax.swing.JTextField txfPn;
    private javax.swing.JTextField txfSn;
    // End of variables declaration//GEN-END:variables
}
